workflows:
  android-release:
    name: Build Android .aab
    environment:
      vars:
        PACKAGE_NAME: "com.rodrigoveiga.contadorsimples"
    scripts:
      - ./gradlew clean
      - ./gradlew bundleRelease
    artifacts:
      - build/app/outputs/bundle/release/*.aab